apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hpa.yaml
- deployment.yaml
- service.yaml
- secret.yaml
secretGenerator:
- literals:
  - username=admins
  - password=1f2d1e2e67df
  name: db-user-pass
- files:
  - config.yaml=config.yaml.encrypted
  name: config.yaml
