apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo
  namespace: test
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: podinfo.co.uk
    http:
      paths:
      - path: /.*
        backend:
          serviceName: podinfo
          servicePort: 9898
