---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: podinfo
  namespace: test
spec:
  hosts:
  - podinfo
  - podinfo.co.uk
  gateways:
  - mesh
  - podinfo-gateway
  http:
  - route:
    - destination:
        name: podinfo.test
        subset: canary
      weight: 10
    - destination:
        name: podinfo.test
        subset: ga
      weight: 90
#  http:
#  - match:
#    - headers:
#        x-user:
#          exact: insider
#      source_labels:
#        release: ga
#    route:
#    - destination:
#        name: podinfo.test
#        subset: canary
#      weight: 100
#  - route:
#    - destination:
#        name: podinfo.test
#        subset: ga
#      weight: 100
