apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-feature-flags
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: feature-flags
data:
  enableCanaryBanner: "true"
  enableExtraMetrics: "true"
  uiTheme: "dev"
