version: 2.1
jobs:
  e2e-kubernetes:
    machine: true
    steps:
      - checkout
      - run:
          name: Build podinfo container
          command: e2e/build.sh
      - run:
          name: Start Kubernetes Kind cluster
          command: e2e/bootstrap.sh
      - run:
          name: Install podinfo with Helm v3
          command: e2e/install.sh
      - run:
          name: Run Helm tests
          command: e2e/test.sh

  push-container:
    docker:
      - image: circleci/golang:1.14
    working_directory: ~/build
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: make build-container
      - run: |
          if [ -z "$CIRCLE_TAG" ]; then
            echo "Not a release, skipping container push";
          else
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin;
            echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io;
            make push-container;
            make push-base;
          fi

  push-binary:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

  push-helm-charts:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: sudo curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && sudo chmod +x /usr/local/bin/kubectl
      - run:
          name: Install helm
          command: sudo curl -L https://storage.googleapis.com/kubernetes-helm/helm-v2.14.2-linux-amd64.tar.gz | tar xz && sudo mv linux-amd64/helm /bin/helm && sudo rm -rf linux-amd64
      - run:
          name: Initialize helm
          command:  helm init --client-only --kubeconfig=$HOME/.kube/kubeconfig
      - run:
          name: Lint charts
          command: |
            helm lint ./charts/*
      - run:
          name: Package charts
          command: |
            mkdir $HOME/charts
            helm package ./charts/* --destination $HOME/charts
      - run:
          name: Publish charts
          command: |
            if echo "${CIRCLE_TAG}" | grep -Eq "[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
              REPOSITORY="https://stefanprodan:${GITHUB_TOKEN}@github.com/stefanprodan/podinfo.git"
              git config user.email stefanprodan@users.noreply.github.com
              git config user.name stefanprodan
              git remote set-url origin ${REPOSITORY}
              git checkout gh-pages
              mv -f $HOME/charts/*.tgz .
              helm repo index . --url https://stefanprodan.github.io/podinfo
              git add .
              git commit -m "Publish Helm charts v${CIRCLE_TAG}"
              git push origin gh-pages
            else
              echo "Not a release! Skip charts publish"
            fi

workflows:
  version: 2
  build-test:
    jobs:
      - e2e-kubernetes
  release:
    jobs:
      - push-binary:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^chart.*/
      - push-container:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^chart.*/
      - push-helm-charts:
          requires:
            - push-container
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^chart.*/