# Default values for ngrok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: stefanprodan/ngrok
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4040

expose:
  service: ga-podinfo:9898

token: 4i3rDinhLqMHtvez71N9S_38rkS7onwv77VFNZTaUR6

nodeSelector: {}

tolerations: []

affinity: {}
