apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../bases/backend
  - ../../bases/frontend
  - ../../bases/cache
  - namespace.yaml
  - feature-flags.yaml
transformers:
  - labels.yaml
patchesStrategicMerge:
  - feature-flag-env.yaml
