apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../../bases/backend
  - ../../bases/frontend
  - ../../bases/cache
  - namespace.yaml
transformers:
  - labels.yaml
