apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/instance: webapp
fieldSpecs:
  - path: metadata/labels
    create: true
