---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: flux
  name: flux
  namespace: ide
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: flux
  template:
    metadata:
      labels:
        name: flux
    spec:
      serviceAccount: flux
      volumes:
      - name: ssh-git
        secret:
          defaultMode: 0400
          secretName: ssh-git
      - name: git-keygen
        emptyDir:
          medium: Memory
      containers:
      - name: flux
        image: quay.io/weaveworks/flux:1.2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030
        volumeMounts:
        - name: ssh-git
          mountPath: /root/.ssh
          readOnly: true
        - name: ssh-git
          mountPath: /etc/fluxd/ssh
          readOnly: true
        - name: git-keygen
          mountPath: /var/fluxd/keygen
        args:
        - --ssh-keygen-dir=/var/fluxd/keygen
        - --k8s-secret-name=ssh-git
        - --git-url=ssh://git@gitsrv/git-server/repos/k8s-podinfo.git
        - --git-branch=master
        - --git-path=deploy/canary
        #- --connect=wss://cloud.weave.works/api/flux
        #- --token=yghrfcs5berdqp68z7wfndcea93rq6nx
