apiVersion: v1
version: 1.4.0
appVersion: 1.4.0
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/k8s-podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/stefanprodan/k8s-podinfo
