apiVersion: v1
version: 4.0.6
appVersion: 4.0.6
name: podinfo
engine: gotpl
description: Podinfo Helm chart for Kubernetes
home: https://github.com/stefanprodan/podinfo
maintainers:
- email: stefanprodan@users.noreply.github.com
  name: stefanprodan
sources:
- https://github.com/stefanprodan/podinfo
