apiVersion: v1
appVersion: "0.4.0"
description: Podinfo Helm chart for Kubernetes
name: podinfo
version: 0.1.0
home: https://github.com/stefanprodan/k8s-podinfo
sources:
- https://github.com/stefanprodan/k8s-podinfo
maintainers:
  - name: stefanprodan
    email: stefanprodan@users.noreply.github.com
engine: gotpl
