{{- $fullname := include "loadtest.fullname" . -}}
{{- $name := include "loadtest.name" . -}}
{{- $chart := include "loadtest.chart" . -}}
{{- $image := .Values.image -}}
{{- range $test := .Values.tests }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullname }}-{{ .name }}
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: loadtest
            image: {{ $image }}
            args:
            - /bin/sh
            - -c
            - "hey -z 55s {{ $test.cmd }} {{ $test.url }}"
          restartPolicy: OnFailure
{{- end -}}
