apiVersion: v1
kind: Service
metadata:
  name: database-replica
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: database-replica
  ports:
    - name: db
      port: 3306
      protocol: TCP
      targetPort: db
