# Default values for backend demo.

# expose the store deployment inside the cluster
host: store

# load balance 80/20 between blue and green
blue:
  replicas: 2
  tag: "0.6.0"
  backend: https://httpbin.org/anything
  weight: 80

green:
  replicas: 2
  tag: "0.6.1"
  backend: https://httpbin.org/anything

externalServices:
  - httpbin.org
