---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-backend-grey
  labels:
    app: podinfo-backend
    color: grey
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
     app: podinfo-backend
     color: grey
  template:
    metadata:
      labels:
        app: podinfo-backend
        color: grey
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:0.6.0-rc.10
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 3
        command:
          - ./podinfo
          - -port=9898
          - -logLevel=debug
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
        env:
          - name: color
            value: "grey"
          - name: message
            value: "Greetings from backend grey"
          - name: backend_url
            value: "http://podinfo-store:9898/echo" #"https://httpbin.org/anything"
