---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-green
  labels:
    app: podinfo
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
     app: podinfo
     color: green
  template:
    metadata:
      labels:
        app: podinfo
        color: green
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: podinfod
        image: quay.io/stefanprodan/podinfo:0.6.0-beta.10
        command:
          - ./podinfo
          - -port=9898
          - -logLevel=debug
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
        env:
          - name: color
            value: "green"
          - name: message
            value: "Greetings from podinfo green"
          - name: backend_url
            value: "http://podinfo-backend:9898/backend"
